greeting_all = [
    ["hello", "Hello! How can I assist you today?"],
    ["hi", "Hi there! What can I do for you?"],
    ["hey", "Hey! How can I help you?"],
    ["greetings", "Greetings! What can I assist you with?"],
    ["good morning", "Good morning! How can I support you?"],
    ["good afternoon", "Good afternoon! What can I help you with?"],
    ['good evening', "Good evening! How may I assist you?"],
    ["good night", "Good night to you too, sweet dreams "],
    ["how are you", "I'm just a program, but I'm here and ready to help! How can I assist you today?"],
    ["sup", "Hey! What can I do for you?"],
    ["yoo", "Yo! How may I help you today?"],
    ["namaste", "Namaste! Aapki kese madad kr sakta hun? use /help to know more"],
    ["good day", "Good day! What can I do for you?"],
    ["howdy", "Howdy! How can I help you today?"],
    ["g'day", "G'day mate! What's on your mind?"],
    ["wassup", "Hey there! Wassup? How can I assist you?"],
    ["hiya", "Hiya! What can I do for you?"],
    ["hail", "Hail, traveler! How can I be of service?"],
    ["namaskar", "Namaskar! Kaise madad kar sakta hoon aapki?"],
    ["kaise ho", "Namaste! Main thik hoon. Aapki kaise madad kar sakta hoon?"],
    ["kese ho", "Namaste! Main thik hoon. Aapki kaise madad kar sakta hoon?"],
    ["kya haal hai", "Hello! Sab kuch thik hai. Kaise madad kar sakta hoon aapki?"],
    ["kya haal he", "Hello! Sab kuch thik hai. Kaise madad kar sakta hoon aapki?"],
    ["pranam", "Pranam! Kaise madad kar sakta hoon aapki?"],
    ["kya chal raha hai", "Hi! Kuch khaas nahi. Kaise madad kar sakta hoon aapki?"],
    ["kya chal rha hai", "Hi! Kuch khaas nahi. Kaise madad kar sakta hoon aapki?"],
    ["kya chal rha h", "Hi! Kuch khaas nahi. Kaise madad kar sakta hoon aapki?"],
    ["kya chal rha he", "Hi! Kuch khaas nahi. Kaise madad kar sakta hoon aapki?"],
    ["kya haal chal hai", "Hello! Sab kuch thik hai. Kaise madad kar sakta hoon aapki?"],
    ["shubh sandhya", "Shubh Sandhya! Kaise madad kar sakta hoon aapki?"],
    ["tu kaisa hain", "Hello! badiya, Aap kaise hain? Kaise madad kar sakta hoon aapki?"],
    ["aap kaise ho", "Hello! badiya, Aap kaise hain? Kaise madad kar sakta hoon aapki?"],
    ["ji aapko", "Ji, aapko kaise madad kar sakta hoon?"],
    ["kem cho", "Kem Cho! How can I assist you today?"],
    ["kaise ho bhai", "thik hun! Bhai, aap kaise ho? Kaise madad kar sakta hoon?"],
    ["aapka swagat hai", "Namaste! Aapka swagat hai. Kaise madad kar sakta hoon aapki?"],
    ["hello dost", "Hello dost! Kaise ho? Kaise madad kar sakta hoon?"],
    ["kya kar rahe ho", "Hi! Kuch khaas nahi. Aap batao, kaise madad kar sakta hoon?"],
    ["kya kr rha h", "Hi! Kuch khaas nahi. Aap batao, kaise madad kar sakta hoon?"],
    ["kya kar rha h", "Hi! Kuch khaas nahi. Aap batao, kaise madad kar sakta hoon?"],
    ["kya kar rha hai", "Hi! Kuch khaas nahi. Aap batao, kaise madad kar sakta hoon?"],
    ["hey zeexx", "Hey! How can I help you?"],
    ["hey jarvis", "Hi there! What can I do for you?"],
    ["hey dtu edubot", "Hi there! What can I do for you?"],
    ["thank you", "You're welcome! I'm here to help."],
    ["thanks", "You're welcome! If you have more questions, feel free to ask."],
    ["thanks a lot", "You're welcome! It's my pleasure to assist you."],
    ["thankful", "I'm glad I could be of help. Is there anything else you need?"],
    ["appreciate it", "You're welcome! I appreciate your kind words."],
    ["grateful", "I'm grateful for the opportunity to assist you. How can I help further?"],
    ["thank you so much", "You're very welcome! If you have more inquiries, let me know."],
    ["thank you sm", "You're very welcome! If you have more inquiries, let me know."],
    ["thanks a million", "You're welcome! A million thanks for reaching out."],
    ["feeling thankful", "I'm also thankful for the interaction! How may I assist you further?"],
    ["thanks heaps", "You're welcome! Thanks heaps for your appreciation."],
    ["expressing gratitude", "I'm here to help anytime. Feel free to express your thoughts or ask questions."],
    ["you've been helpful", "I'm glad to have been of help! If you need anything else, just let me know."],
    ["thanks for your help", "You're welcome! Thanks for reaching out. Is there anything else on your mind?"],
    ["you made a difference", "I'm happy to have made a difference! Let me know if there's anything else I can do."],
    ["dhanyavaad", "Aapka swagat hai! Kuch aur poochna ho toh poochiye."],
    ["shukriya", "Koi baat nahi! Kuch aur poochna ho toh bataiye."],
    ["how are you doing", "I don't experience emotions, but thanks for asking! How can I assist you?"],
    ["how's it going", "As a program, I don't have personal experiences, but I'm here and ready to help. What can I do for you?"],
    ["how is it going", "As a program, I don't have personal experiences, but I'm here and ready to help. What can I do for you?"],
    ["what's up", "Not much! I'm here, ready to assist you. What can I help you with today?"],
    ["whats up", "Not much! I'm here, ready to assist you. What can I help you with today?"],
    ["what's happening", "Not much on my end! How can I assist you today?"],
    ["what is happening", "Not much on my end! How can I assist you today?"],
    ["whats happening", "Not much on my end! How can I assist you today?"],
    ["how's everything", "I'm doing well in the virtual world! How can I assist you?"],
    ["how's life", "I don't have a life, but I'm here to help with whatever you need!"],
    ["how is life", "I don't have a life, but I'm here to help with whatever you need!"],
    ["how you doing", "I'm doing well in the digital realm! What can I do for you?"],
    ["how's your day", "Every day is a good day in the virtual world! How can I assist you?"],
    ["how is your day", "Every day is a good day in the virtual world! How can I assist you?"],
    ["how was your day", "Every day is a good day in the virtual world! How can I assist you?"],
    ["how have you been", "I'm always here and ready to help! What can I do for you today?"],
    ["how's the weather", "I don't have a sense of weather, but I'm ready to assist you with any questions you have!"],
    ["how are things", "Things are good in my world! How can I assist you in your world?"],
    ["how's the day treating you", "Days don't affect me, but I'm ready to assist you. How can I help?"],
    ["what's the latest", "I'm always up to date! How can I assist you with the latest information?"],
    ["how are you holding up", "I'm holding up well, thanks for asking! How can I assist you today?"],
    ["how's your virtual existence", "My virtual existence is thriving! How can I assist you in this digital realm?"],
    ["how's the virtual world", "The virtual world is stable and ready for your inquiries! How can I assist you?"],
    ["how are you feeling", "I don't have feelings, but I'm here to assist you. What can I help you with today?"],
    ["how are you coping", "I don't experience challenges, but I'm here to help you with yours! What can I assist you with?"],
    ["aap kaise hain", "Main hamesha taiyar hoon madad karne ke liye! Aapka kya sawaal hai?"],
    ["aap kaise hai", "Main sirf ek program hoon, mere paas koi bhi bhavna nahi hai, lekin main yahaan hoon aapki madad ke liye. Kaise madad kar sakta hoon?"],
    ["kaise ho", "Main sirf ek program hoon, mere paas koi bhi bhavna nahi hai, lekin main yahaan hoon aapki madad ke liye. Kaise madad kar sakta hoon?"],
    ["how's your day going", "Days don't affect me, but I'm here and ready to assist you. What can I help you with today?"],
    ["how is your day going", "Days don't affect me, but I'm here and ready to assist you. What can I help you with today?"],
    ["how's your virtual day", "Every day is a good day in the virtual world! How can I assist you on this virtual day?"],
    ["how's the digital realm treating you", "The digital realm is treating me well! How can I assist you in this digital space?"],
    ["what's new with you", "Not much changes for me, but I'm ready to help with anything new you have in mind. How can I assist you?"],
    ["what is new with you", "Not much changes for me, but I'm ready to help with anything new you have in mind. How can I assist you?"],
    ['help', 'You can get help or the idea of how this bot works by command /help'],
    [" pyq", 'use /help command to know how to use /pyq command'],
    ["pyq ", 'use /help command to know how to use /pyq command'],
    [" note", 'use /help command to know how to use /notes command'],
    ["note ", 'use /help command to know how to use /notes command'],
    [" assignment", 'use /help command to know how to use /assignment command'],
    ["assignment ", 'use /help command to know how to use /assignment command'],
    [" playlist", 'use /help command to know how to use /playlist command'],
    ["playlist ", 'use /help command to know how to use /playlist command'],
    [" book", 'use /help command to know how to use /books command'],
    ["book ", 'use /help command to know how to use /books command'],
    ["resource", 'use /help command to know how to use the bot to get resources'],
    [" notice", 'use /help command to know how to use /dtu_notices command'],
    ["notice ", 'use /help command to know how to use /dtu_notices command'],
    [" event", 'use /help command to know how to use /dtu_events command'],
    ["event ", 'use /help command to know how to use /dtu_events command'],
    [" available", 'If you want to know available resources, just use /available_pyq or /available_books etc.'],
    ["available ", 'If you want to know available resources, just use /available_pyq or /available_books etc.'],
]


abuses_negativity = [
    "madarchod", "chutiya", "chutiye" ,"kutte", "kutta", "gandiye", "kamina", "behanchod", "fuck you", "chut", "bencho", "bhosdike", "bsdk", "bhenchod", "bitch", "bich",
    "nigga", "bkl", "motherfucker", "sisterfucker", "cunt", "vagina", "pussy", "asshole", "kamine", "pencho", "behancho", "rand", "r word", "bhen ke lode", "lode"
]

humour = [
    ""
]